# Pipeline to generate Kubernetes configuration and Codefresh files

# Required Variables

# Parent Pipeline Variables
# APPLICATION_NAME
# The name of the Application possibly CF_REPO_NAME as a default
# CONFIGURATIONS_REPOSITORY
# - Name of VCS Repository containing configuration files.
# ISC_REPOSITORY
# - Name of VCS Repository containing Codefresh configuration files.  ISC or Internal Shared Configurations.
# GIT_INTEGRATION_NAME
# - Name of GIT Pipeline Integration.
# FQDN_IMAGE
# - Combination of Image registry domain + registry name + image name
# IMAGE_TAG
# - Tag for Container Image.

version: '1.0'
stages:
  - clone
  - create
  - commit

steps:
  clone:
    type: parallel
    steps:
    # Clone Configurations Repository
      clone_apps:
        title: Cloning Configurations Repository...
        type: git-clone
        repo: ${{CF_REPO_OWNER}}/${{CONFIGURATIONS_REPOSITORY}}
        revision: main
        git: ${{GIT_INTEGRATION_NAME}}

    # Clone ISC Repository
      clone_isc:
        title: Cloning ISC Repository...
        type: git-clone
        repo: ${{CF_REPO_OWNER}}/${{ISC_REPOSITORY}}
        revision: master
        git: ${{GIT_INTEGRATION_NAME}}
    stage: clone

  create:
    type: parallel
    steps:
    # Create Configuration Files
      create_kubernetes_files:
        title: Creation Configuration Files...
        type: freestyle
        image: quay.io/codefresh-contrib/yq:4
        working_directory: ${{clone_apps}}
        commands:
          - echo 'Creating Configurations files...'
          - mkdir ${{APPLICATION_NAME}}
          - cp -a ./templates/kustomize/. ./${{APPLICATION_NAME}}/
          - cd ${{APPLICATION_NAME}}
          - echo 'Replacing placeholders in Configurations files...'
          - echo 'Replacing application-name with ${{APPLICATION_NAME}}'
          - grep -rl 'application-name' . | xargs sed -i -e 's|application-name|${{APPLICATION_NAME}}|g'
          - echo 'Replacing fqdn-image with ${{FQDN_IMAGE}}'
          - grep -rl 'fqdn-image' . | xargs sed -i -e 's|fqdn-image|${{FQDN_IMAGE}}|g'
          - echo 'Replacing image-tag with ${{IMAGE_TAG}}'
          - grep -rl 'image-tag' . | xargs sed -i -e 's|image-tag|${{IMAGE_TAG}}|g'
          - echo 'Completed Configuration file changes...'
          - cat ./*/*.yaml

    # Create Codefresh Files
      create_codefresh_files:
        title: Creation Codefresh Files...
        type: freestyle
        image: quay.io/codefresh-contrib/yq:4
        working_directory: ${{clone_isc}}/resources/configurations/products
        commands:
          - echo 'Creating Codefresh files...'
          - cp ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/templates/codefresh/products/product.yaml ${{APPLICATION_NAME}}.yaml
          - echo 'Replacing placeholders in Codefresh files...'
          - sed -i -e 's/application-name/${{APPLICATION_NAME}}/g' ${{APPLICATION_NAME}}.yaml
          - echo 'Completed Codefresh file changes...'
          - cat ./${{APPLICATION_NAME}}.yaml
    stage: create

  commit_and_push:
    type: parallel
    steps:
    # Commit Configuration Files
      commit_and_push_configuration_files:
        title: Committing New Configuration Files...
        type: git-commit
        arguments:
          repo: ${{CF_REPO_OWNER}}/${{CONFIGURATIONS_REPOSITORY}}
          git: ${{GIT_INTEGRATION_NAME}}
          working_directory: '${{CF_VOLUME_PATH}}/${{CONFIGURATIONS_REPOSITORY}}'
          commit_message: 'Adding Configuration files for ${{APPLICATION_NAME}}'
          git_user_name: codefresh-automation
          git_user_email: automation@codefresh.io
          rebase: true

    # Commit Codefresh Files
      commit_and_push_codefresh_files:
        title: Committing New Codefresh Files...
        type: git-commit
        arguments:
          repo: ${{CF_REPO_OWNER}}/${{ISC_REPOSITORY}}
          git: ${{GIT_INTEGRATION_NAME}}
          working_directory: '${{CF_VOLUME_PATH}}/${{ISC_REPOSITORY}}'
          commit_message: 'Adding Codefresh files for ${{APPLICATION_NAME}}'
          git_user_name: codefresh-automation
          git_user_email: automation@codefresh.io
          rebase: true
    stage: commit