apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization

resources:
- ../../base
# TODO: Select a secrets manager https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/
# Secrets should not be stored in the repository, they need to be fetch via Secrets Controller

patches:
- target:
    kind: Rollout
    name: microservice-a
  path: replace.yaml