apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-c
  name: microservice-c
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: microservice-c
