apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: microservice-a
  name: microservice-a
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: microservice-a
  strategy:
    blueGreen:
      activeService: microservice-a
      autoPromotionEnabled: true
      previewService: microservice-a-preview
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
        - image: full_image_name:84cc527
          imagePullPolicy: Always
          name: microservice-a
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always